# Generated by Django 5.1.4 on 2024-12-09 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppPOS', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='stock',
        ),
    ]
