# Generated by Django 5.1.4 on 2024-12-09 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppPOS', '0002_remove_producto_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroventa',
            name='cantidad',
        ),
    ]
